services:

  dev:
    build: ./build/dev
    command: sleep infinity
    volumes:
      - ../.:/workspace
    environment:
      DATABASE_URL: "mysql://root:passw0rd@database:3306/app"
      MAILER_DSN: "smtp://mailer:1025"
      
  database:
    extends:
      file: ../docker-compose.yml
      service: database

  mailer:
    extends:
      file: ../docker-compose.yml
      service: mailer

volumes:
  mysql-data:
